### ISSUE TITLE
Installation according to README fails.

### ISSUE THREAD

**Issue by yspreen** [apexatoll/aoc-cli#3]
This is my process:

```
➜  ~ brew install pandoc
Updating Homebrew...
==> Auto-updated Homebrew!
######################################################################## 100.0%
==> Pouring pandoc-2.11.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pandoc/2.11.4: 10 files, 146.0MB
➜  ~ sudo gem install aoc_cli
Password:
Fetching aoc_cli-0.1.3.gem
Fetching colorize-0.8.1.gem
Fetching pandoc-ruby-2.1.4.gem
Fetching curb-0.9.11.gem
Successfully installed colorize-0.8.1
Building native extensions. This could take a while...
ERROR:  Error installing aoc_cli:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/curb-0.9.11/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210219-55535-vekesv.rb extconf.rb
checking for curl-config... yes
checking for curlopt_tcp_keepalive... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
        from extconf.rb:52:in `block in have_constant'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from extconf.rb:44:in `have_constant'
        from extconf.rb:62:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/curb-0.9.11/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/curb-0.9.11 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/curb-0.9.11/gem_make.out
➜  ~ 
```

**Comment by yspreen** [comment]
According to [this](https://stackoverflow.com/a/65262186/2585092) SO answer, I should install xcode dev tools (`xcode-select --install `). That was already done. I continued by upgrading ruby with `brew install ruby`. Didn't help either

**Comment by yspreen** [comment]
No idea what the following cmd does, but it works?

`sudo xcode-select -switch /`

**Comment by yspreen** [comment]
So i guess just add that step as a precursor to the readme for macos users. Then it should be good

**Comment by apexatoll** [comment]
Thanks for the feedback. This issue is more related to the installation of xcode on your machine rather than aoc-cli itself so I do not think it is necessary to add these steps to the documentation.  The vast majority of macOs CLI users will already have xcode installed in order to be able to code in most popular languages on their mac - I will however add xcode to the dependencies

**Comment by yspreen** [comment]
I had Xcode installed, but I still had the issue described in #3. I'd say many people might have the exact same problem. Betting on them being familiar with ruby and ruby gems to be able to use this projects seems like a bad idea

**Comment by yspreen** [comment]
This shouldn't be closed

**Comment by yspreen** [comment]
Okay, I just saw the added comment in the readme. Thanks for that. I'm an iOS developer by day though, so I use the Xcode tools a lot. So I had them installed. Ruby however seems to require some special configuration that I'm unfamiliar with, hence the confusion about this `-switch` command.

Even with the added comment in the README, the installation would still have failed for me and I would've had to research the error message. Maybe consider adding this hint (and the switch command) to the readme to fully resolve the issue. Thanks.

(paging @apexatoll )
